preferred-ips: Fix tiny formatting overlook

diff --git a/deploy/preferred-ip b/deploy/preferred-ip
--- a/deploy/preferred-ip
+++ b/deploy/preferred-ip
@@ -26,7 +26,7 @@ for host in $hosts; do
 		fi
 	done
 
-	echo -e "\nError: Can't reach host $host, tried pinging $(echo $candidates | xargs)" >&2
+	echo -e "Error: Can't reach host $host, tried pinging $(echo $candidates | xargs)" >&2
 
 done
 
